#!/bin/bash

# labextensions
jupyter labextension install --clean @jupyter-widgets/jupyterlab-manager \
                                      @jupyterlab/server-proxy \
                                      @jupyterlab/geojson-extension \
                                      @pyviz/jupyterlab_pyviz \
                                      jupyter-matplotlib \
                                      jupyter-leaflet \
                                      dask-labextension \

# Some extra r packages.
Rscript -e "remotes::install_github('BigelowLab/ohwobpg')"
Rscript -e "remotes::install_github('https://github.com/BigelowLab/rasf')"
Rscript -e "install.packages('biomod2', repos = 'https://cloud.r-project.org/')"
# Rscript -e "remotes::install_github('iobis/robis')"

#  This is a test if the right proj library is loaded.
python -c "import cartopy; import cartopy.crs; print(cartopy.__version__)"

# Error installing vscode extensions, comment out for now:
# Extension 'ms-python.python' not found.
# Make sure you use the full extension ID, including the publisher, e.g.: ms-vscode.csharp
# error undefined
#code-server --install-extension ms-python.python

# Install the VS code proxy (now from conda-forge in environment.yml)
#pip install git+git://github.com/betatim/vscode-binder#egg=jupyter_vscode_proxy

# EOF
