#!/bin/bash -l

# ==== ONLY EDIT WITHIN THIS BLOCK =====
# No longer install development version, it's included in environment.yml
#pip install -e git+https://github.com/icesat2py/icepyx.git#egg=icepyx --src /srv/icesat2py

mkdir -p ${HOME}/my-conda-envs/
cp /tmp/.condarc ${HOME}/.condarc

# ==== ONLY EDIT WITHIN THIS BLOCK =====
exec "$@"
