name: OHW-r
channels:
  - conda-forge
dependencies:
  # base
  - python=3.10
  - pangeo-notebook=2023.07.21
  - nb_conda_kernels
  - jupyter-rsession-proxy
  # 2/24/23: Added jsonschema-with-format-nongpl to address a deployment error
  - jsonschema-with-format-nongpl
  - gh
  - nano
  - mamba
  # - curl
  # - git
  # - wget
  # - tar
  # - vim
  # R packages
  - r-base >=4
  # - rstudio
  - r-abind
  - r-akima
  - r-ape
  - r-automap
  - r-biomod2
  - r-bitops
  - r-caret
  - r-catools
  - r-checkmate
  - r-commonmark
  - r-cowplot
  - r-crul
  - r-dbi
  - r-devtools
  - r-dichromat
  - r-dismo
  - r-doparallel
  - r-dplyr
  - r-earth
  - r-rerddap
  - r-foreach
  - r-foreign
  - r-fracdiff
  - r-gbm >=2.1.3
  - r-geometry
  - r-geosphere
  - r-ggplot2
  - r-glmnet
  - r-gridextra
  - r-gsw
  - r-hexbin
  - r-httpcache
  - r-httr
  - r-igraph
  - r-irkernel
  - r-jsonlite
  # - r-keras # keras and tensorflow cause our images to become much larger
  # Which can cause problems with Github Actions running out of storage https://github.com/docker/build-push-action/issues/321
  - r-knitr
  - r-lattice
  - r-leaflet
  - r-littler
  - r-lmtest
  - r-lpsolve
  - r-lubridate
  - r-mmand
  - r-mapdata
  - r-mapedit
  - r-maps
  - r-maptools
  - r-marmap
  - r-markdown
  - r-mass
  - r-mda
  - r-metr
  - r-ncdf4
  - r-nnet
  - r-oce
  - r-ocedata
  - r-rosm
  - r-palmerpenguins
  - r-patchwork
  - r-PCICt
  - r-plotly
  - r-proc >=1.15.0
  - r-ps>=1.3.4
  - r-purrr
  - r-r.utils
  - r-randomforest
  - r-rann
  - r-raster >=1.4.3
  - r-rastervis
  - r-readr
  - r-remotes
  - r-reshape
  - r-rgdal >=1.5
  - r-rgeos
  - r-rlang
  - r-rmarkdown
  - r-rnaturalearth
  - r-rnaturalearthdata
  - r-robis
  - r-rpart
  - r-rsqlite
  - r-rstackdeque
  - r-rvest
  - r-s2
  - r-scales
  - r-sf >=0.9_5
  - r-sp
  - r-stars
  - r-terra
  - r-tibble
  - r-tidyr
  - r-tidygraph
  - r-tidyverse
  - r-tiff
  - r-tmap
  - r-tmaptools
  - r-tseries
  - r-tsibble
  - r-tzdb
  - r-udunits2
  - r-urca
  - r-vegan
  - r-viridis
  - r-vroom
  - r-wdpar
  - r-xaringan
  - r-xml2
  - r-xts
  # - rpy2
