name: Generate short SHA

on:
  workflow_call:
    outputs:
      shortsha:
        description: A shortened version of the current commit's SHA
        value: ${{ jobs.shortsha.outputs.shortsha }}
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  shortsha:
    name: Generate Short SHA for Docker tag
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Generate Short SHA
        id: shortsha
        run: echo "shortsha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

    outputs:
      shortsha: ${{steps.shortsha.outputs.shortsha}}
